# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

name: CI Doc Shim

on:
  pull_request:
    branches: [main]
    types: [milestoned, opened, synchronize]

# Permissions for the GITHUB_TOKEN used by the workflow.
permissions:
  contents: read # Allows reading the content of the repository.

jobs:
  validate:
    strategy:
      matrix:
        type: [install, upgrade]
        flavor: [upstream, registry1, unicorn]
    uses: defenseunicorns/uds-common/.github/workflows/callable-ci-docs-shim.yaml@7826099a1ceb4657f9cd502968dea8e0e7753ac6 # v1.7.0
    with:
      flavor: ${{ matrix.flavor }}
      type: ${{ matrix.type }}
    secrets: inherit # Inherits all secrets from the parent workflow.
